name: Tarea
title: "T - "
description: Plantilla para registrar una nueva tarea.
labels: ["task"]
projects: ["PlayerCodeDev/7"]
assignees:
  - PlayerCodeDev
body:
  - type: markdown
    attributes:
      value: |
        ### Tarea

        Añade y completa la siguiente información de forma clara y precisa para el desarrollo de la tarea.

  - type: textarea
    id: task-description
    attributes:
      label: Descripción de la Tarea
      description: ¿Qué se debe hacer exactamente en esta tarea?
      placeholder: "Implementar validación de formularios de inicio de sesión."
    validations:
      required: true

  - type: dropdown
    id: technical-area
    attributes:
      label: Área Técnica
      description: Clasifica esta trarea por área de trabajo.
      options:
        - Frontend
        - Backend
        - Full Stack
        - Base de Datos
        - Testing
        - Documentación
        - Infraestructura
        - Otro
      default: 7

  - type: textarea
    id: additional-notes
    attributes:
      label: Notas Adicionales (opcional)
      description: Detalles técnicos, decisiones clave o enlaces útiles.
      placeholder: |
        - Considerar lógica de errores del backend.
        - Código fuente: `src/pages/login.jsx`.
        - Diseño: Figma -> Login form v2.
