name: Historia de Usuario
title: "HU - "
description: Plantilla para registrar una nueva historia de usuario.
labels: ["user story"]
projects: ["PlayerCodeDev/7"]
assignees:
  - PlayerCodeDev
body:
  - type: markdown
    attributes:
      value: |
        ### Historia de Usuario

        Añade la siguiente información para crear una historia de usuario, agregando información clara y precisa para su desarrollo.

  - type: textarea
    id: user-story-description
    attributes:
      label: Descripción de la Historia de Usuario
      description: Usa el formato como [tipo de usuario] quiero [acción o funcionalidad] para [beneficio o razón].
